version: "3.2"

services:
    nginx:
        image: nginx:latest
        ports:
            - 8080:80
            - 443:443
        volumes:
            - ./app:/app
            - ./site.conf:/etc/nginx/conf.d/default.conf 
        links:
            - php
    php:
        image: php:7-fpm
        volumes:
        - ./app:/app